//! WirePlumber 0.5+ persistence: renders Sink's routing assignments as a
//! declarative `stream.rules` config fragment in
//! `~/.config/wireplumber/wireplumber.conf.d/90-sink-routing.conf`.
//!
//! WirePlumber reads conf fragments at startup only, so this takes effect
//! from the next login / WirePlumber restart. Live enforcement of
//! assignments while Sink is running happens in `commands::devices` via the
//! regular stream poll. (WirePlumber 0.4 used Lua rules; 0.5 replaced them
//! with the SPA-JSON conf fragments rendered here.)

use std::fs;
use std::path::PathBuf;

use crate::error::SinkError;
use crate::persistence::assignments::Assignments;

pub fn conf_path() -> Result<PathBuf, SinkError> {
    let dir = dirs::config_dir()
        .ok_or_else(|| SinkError::Config("cannot resolve the user config directory".into()))?;
    Ok(dir
        .join("wireplumber")
        .join("wireplumber.conf.d")
        .join("90-sink-routing.conf"))
}

/// Escape a string for use inside a double-quoted SPA-JSON value.
/// App names come from untrusted stream properties; control characters
/// (newlines etc.) would break out of the quoted string, so drop them.
fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            c if c.is_control() => {}
            c => out.push(c),
        }
    }
    out
}

/// Render the conf fragment. Returns None when there are no assignments
/// (the file should be removed instead).
pub fn render(assignments: &Assignments) -> Option<String> {
    if assignments.assignments.is_empty() {
        return None;
    }

    let mut out = String::from(
        "# Generated by Sink (audio mixer). Do not edit — regenerated on every\n\
         # routing change. Routes app streams to Sink's virtual channels.\n\
         stream.rules = [\n",
    );
    for a in &assignments.assignments {
        out.push_str(&format!(
            "  {{\n    matches = [\n      {{ \"{}\" = \"{}\" }}\n    ]\n    actions = {{\n      update-props = {{\n        target.object = \"{}\"\n      }}\n    }}\n  }}\n",
            escape(&a.match_prop),
            escape(&a.match_value),
            escape(&a.sink_name),
        ));
    }
    out.push_str("]\n");
    Some(out)
}

/// Write the fragment to disk, or remove it when no assignments remain.
pub fn write(assignments: &Assignments) -> Result<(), SinkError> {
    let path = conf_path()?;
    match render(assignments) {
        Some(content) => {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(&path, content)?;
        }
        None => {
            if path.exists() {
                fs::remove_file(&path)?;
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_rule_per_assignment() {
        let mut a = Assignments::default();
        a.set("application.name", "spotify", "sink_music");
        a.set("node.name", "audio-src", "sink_system");

        let conf = render(&a).expect("non-empty assignments render");
        assert!(conf.contains("stream.rules = ["));
        assert!(conf.contains("{ \"application.name\" = \"spotify\" }"));
        assert!(conf.contains("target.object = \"sink_music\""));
        assert!(conf.contains("{ \"node.name\" = \"audio-src\" }"));
        assert!(conf.contains("target.object = \"sink_system\""));
    }

    #[test]
    fn empty_assignments_render_nothing() {
        assert!(render(&Assignments::default()).is_none());
    }

    #[test]
    fn escapes_quotes_and_backslashes() {
        let mut a = Assignments::default();
        a.set("application.name", "we\"ird\\app", "sink_game");
        let conf = render(&a).expect("renders");
        assert!(conf.contains(r#""we\"ird\\app""#));
    }
}
